image: openjdk:11-jdk

variables:

  ANDROID_COMPILE_SDK: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  ANDROID_SDK_TOOLS: "11076708_latest"

# Packages installation before running script
before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}.zip
  - unzip -d android-sdk-linux android-sdk.zip
  - echo y | android-sdk-linux/cmdline-tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" >/dev/null 


stages:          # List of stages for jobs, and their order of execution
  - build
  - verify
  - unit-test
  - package
  - release
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
  artifacts:
    paths:
      - app/build/outputs/

verify-job:
  stage: verify
  script:
    - echo "Esegui i controlli di verifica qui"

unit-test-job:
  stage: unit-test
  script:
    - echo "Esegui i test unitari qui"

package-job:
  stage: package
  script:
    - echo "Crea il pacchetto dell'app qui"

release-job:
  stage: release
  script:
    - echo "Prepara la release qui"

deploy-job:
  stage: deploy
  script:
    - echo "Effettua il deploy qui"